### ISSUE TITLE
where is aria2?

### ISSUE THREAD

**Issue by Uzibird** [codysk/bgmi-docker-all-in-one#1]
it's need i install the aria2 in the docker?  or it can ues aria2 in my host?

**Comment by codysk** [comment]
No, this image contains transmission service as downloader
you can also use aria2 at your host by bgmi config command line if you want.

**Comment by Uzibird** [comment]
All right,I can use aria2 it's on my host.And successfully added the task to aria2,the download was successful, but why there is no file locally

**Comment by codysk** [comment]
You should check your aria2 task detail and docker container fs mount.
Why dont you use transmission as downloader?  You just need mount /bgmi directory to your host.
Anything else is preconfigured by this project.

**Comment by Uzibird** [comment]
I also have this problem with the transmission. 
aria2 shows that the download is successful and the network speed is not 0, it can successfully create bgmi/anime but no bgmi/anime/anime.mp4
It often occurs with this problem 
bash-4.4# bgmi update --download
 [*] marking bangumi status ...
 [*] updating subscriptions ...
 [*] fetching psychometrics 3 ...
 [*] Re-downloading ...
Did not send a download task
