### ISSUE TITLE
突然fetch不到数据了

### ISSUE THREAD

**Issue by BiFangKNT** [codysk/bgmi-docker-all-in-one#13]
之前用得好好的，今天突然fetch不到数据了，尝试过清除数据重装容器，没有效果。
具体情况：
输入命令：bgmi fetch "xxx"
久久没有回应。
于是我切换数据源试试：bgmi source bangumi_moe（之前是蜜柑计划）
然后：bgmi cal，返回：
2023-04-21 07:27:46 WARNING | Warning: no bangumi schedule, fetching ...                                                             
2023-04-21 07:27:46 INFO    | Fetching bangumi info ...
经过漫长的等待也没有回复（之前有试过有返回的，返回：error:failed to establish a new connection，但是后来不知怎的连这个返回都没有了）
我注意到，这个返回的时间和系统时间不一致，容器里的时间是七点，而系统时间是十五点，不知道这个会不会有影响。

**Comment by BiFangKNT** [comment]
> 
备注：这个评论里的操作除了第一步的fetch之外，都是在我清除除了下载的动画之外所有数据，然后删除容器，拉取最新的1.3.6版本之后进行的。
我写这个问题的时候，bgmi cal一直在跑着，而在我写这个备注时已经过了有十分钟了，终于是有了返回
返回如下：
Traceback (most recent call last):                                                                                                   
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn                                             
    conn = connection.create_connection(                                                                                             
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection                                 
    raise err                                                                                                                        
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection                                 
    sock.connect(sa)                                                                                                                 
TimeoutError: [Errno 110] Operation timed out                                                                                        
                                                                                                                                     
During handling of the above exception, another exception occurred:                                                                  
                                                                                                                                     
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen                                           
    httplib_response = self._make_request(                                                                                           
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request                                     
    self._validate_conn(conn)                                                                                                        
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn                                   
    conn.connect()                                                                                                                   
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect                                               
    self.sock = conn = self._new_conn()                                                                                              
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn                                             
    raise ConnectTimeoutError(                                                                                                       
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f2cd167b490>, 'Connection to mikanani.me ti
med out. (connect timeout=None)')                                                                                                    
                                                                                                                                     
During handling of the above exception, another exception occurred:                                                                  
                                                                                                                                     
Traceback (most recent call last):                                                                                                   
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send                                                   
    resp = conn.urlopen(                                                                                                             
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen                                           
    return self.urlopen(                                                                                                             
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen                                           
    return self.urlopen(                                                                                                             
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen                                           
    return self.urlopen(                                                                                                             
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen                                           
    retries = retries.increment(                                                                                                     
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment                                             
    raise MaxRetryError(_pool, url, error or ResponseError(cause))                                                                   
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: / (Caused by Conn
ectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2cd167b490>, 'Connection to mikanani.me timed out. (connect timeout
=None)'))
                                                                                                                                     
During handling of the above exception, another exception occurred:                                                                  
                                                                                                                                     
Traceback (most recent call last):                                                                                                   
  File "/usr/bin/bgmi", line 8, in <module>                                                                                          
    sys.exit(main())                                                                                                                 
  File "/usr/lib/python3.10/site-packages/bgmi/main.py", line 51, in main                                                            
    cli.main(prog_name="bgmi")                                                                                                       
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main                                                         
    rv = self.invoke(ctx)                                                                                                            
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke                                                       
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                          
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke                                                       
    return ctx.invoke(self.callback, **ctx.params)                                                                                   
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke                                                        
    return __callback(*args, **kwargs)                                                                                               
  File "/usr/lib/python3.10/site-packages/bgmi/main.py", line 343, in calendar                                                       
    weekly_list = ctl.cal(force_update=force_update, cover=cover)                                                                    
  File "/usr/lib/python3.10/site-packages/bgmi/lib/controllers.py", line 197, in cal                                                 
    website.fetch()                                                                                                                  
  File "/usr/lib/python3.10/site-packages/bgmi/website/base.py", line 52, in fetch                                                   
    bangumi_result = self.fetch_bangumi_calendar()                                                                                   
  File "/usr/lib/python3.10/site-packages/bgmi/website/mikan.py", line 351, in fetch_bangumi_calendar                                
    for update_time, day in get_weekly_bangumi():                                                                                    
  File "/usr/lib/python3.10/site-packages/bgmi/website/mikan.py", line 52, in get_weekly_bangumi                                     
    r = get_text(server_root)                                                                                                        
  File "/usr/lib/python3.10/site-packages/bgmi/website/mikan.py", line 161, in get_text                                              
    r = requests.get(url, params=params)                                                                                             
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get                                                    
    return self.request("GET", url, **kwargs)                                                                                        
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request                                                
    resp = self.send(prep, **send_kwargs)                                                                                            
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send                                                   
    r = adapter.send(request, **kwargs)                                                                                              
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 553, in send                                                   
    raise ConnectTimeout(e, request=request)                                                                                         
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: / (Caused by Co
nnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2cd167b490>, 'Connection to mikanani.me timed out. (connect timeo
ut=None)'))

**Comment by codysk** [comment]
看起来你那儿连不上 mikan 的样子，看异常是重连很多次都超时了

**Comment by BiFangKNT** [comment]
> 看起来你那儿连不上 mikan 的样子，看异常是重连很多次都超时了

不是，我这里已经是切到bangumi_moe了。之前都能正常连的，咋突然连不上了呢

**Comment by codysk** [comment]
> 不是，我这里已经是切到bangumi_moe了。之前都能正常连的，咋突然连不上了呢

那次报错的fetch应该是你切换数据源之前挂着跑的，那会儿数据源切换还没有生效，至于网络问题可以在容器内用wget/curl之类的工具确认下。（部分地区一些站点突然间无法访问确实也不少见的

**Comment by BiFangKNT** [comment]
> > 不是，我这里已经是切到bangumi_moe了。之前都能正常连的，咋突然连不上了呢
> 
> 那次报错的fetch应该是你切换数据源之前挂着跑的，那会儿数据源切换还没有生效，至于网络问题可以在容器内用wget/curl之类的工具确认下。（部分地区一些站点突然间无法访问确实也不少见的

没有，我切数据源之前就fetch不到数据了。我之前切数据源只要几秒钟就能cal到列表的。另外求教一下，你说的wget/curl之类的工具，具体的命令是什么啊

**Comment by codysk** [comment]
```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: / (Caused by Co
nnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2cd167b490>, 'Connection to mikanani.me timed out. (connect timeo
ut=None)'))
```
你的报错信息已经写得很清楚了，尝试连接 mikanani.me 的时候网络超时了，至于具体为什么突然网络出问题，你需要排查你本地的网络状况。

确认容器环境连不连得上mikan的话可以尝试下面的命令。
```
apk --update add wget curl
curl -Lv https://mikanani.me
wget -O - https://mikanani.me
```

**Comment by BiFangKNT** [comment]
> 
第一条命令没有反应，第二条命令返回：
*   Trying 174.37.243.85:443...                                                                                                      
*   Trying [2a03:2880:f10f:83:face:b00c:0:25de]:443...                                                                               
* Immediate connect fail for 2a03:2880:f10f:83:face:b00c:0:25de: Address not available
第三条命令也没啥反应，应该是连不上。
可是此前我已经在docker部署了clash，用的是我平时在用的节点，在群晖控制面板里也指定了代理服务器，上套件商店啥的时候，在yacd前端里也能看到正常的有连接，流量有使用，bgmi怎么会连不上呢，，

**Comment by codysk** [comment]
> > 
> 
> 第一条命令没有反应，第二条命令返回：
> 
> *   Trying 174.37.243.85:443...                                                                                                      
> 
> *   Trying [2a03:2880:f10f:83:face:b00c:0:25de]:443...                                                                               
> 
> * Immediate connect fail for 2a03:2880:f10f:83:face:b00c:0:25de: Address not available
> 
> 第三条命令也没啥反应，应该是连不上。
> 
> 可是此前我已经在docker部署了clash，用的是我平时在用的节点，在群晖控制面板里也指定了代理服务器，上套件商店啥的时候，在yacd前端里也能看到正常的有连接，流量有使用，bgmi怎么会连不上呢，，

那你要排查你的容器环境了，我建议你先试试不要过这些代理之类的网络设置。（毕竟总好过现在哪儿都连不上了
但具体是你哪个环节造成的网络问题我就没法这样帮你排障了。

**Comment by BiFangKNT** [comment]
> 
我关闭代理后，第一条命令有回应了：
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz                                                        
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz                                                   
(1/3) Installing libunistring (1.1-r0)                                                                                               
(2/3) Installing libidn2 (2.3.4-r0)                                                                                                  
(3/3) Installing wget (1.21.3-r2)                                                                                                    
Executing busybox-1.35.0-r29.trigger                                                                                                 
OK: 1116 MiB in 79 packages 
话说这第一条命令是用来干什么的？

第二条命令的回应：
*   Trying 199.96.62.21:443...                                                                                                       
*   Trying [2a03:2880:f10d:83:face:b00c:0:25de]:443...                                                                               
* Immediate connect fail for 2a03:2880:f10d:83:face:b00c:0:25de: Address not available                                               
* connect to 199.96.62.21 port 443 failed: Operation timed out                                                                       
* Failed to connect to mikanani.me port 443 after 127262 ms: Couldn't connect to server                                              
* Closing connection 0                                                                                                               
curl: (28) Failed to connect to mikanani.me port 443 after 127262 ms: Couldn't connect to server

第三条命令的回应：
--2023-04-22 12:37:31--  https://mikanani.me/                                                                                        
Resolving mikanani.me (mikanani.me)... 199.96.62.21, 2a03:2880:f126:83:face:b00c:0:25de                                              
Connecting to mikanani.me (mikanani.me)|199.96.62.21|:443... failed: Operation timed out.                                            
Connecting to mikanani.me (mikanani.me)|2a03:2880:f126:83:face:b00c:0:25de|:443... failed: Address not available.                    
Retrying.                                                                                                                            
                                                                                                                                     
--2023-04-22 12:39:39--  (try: 2)  https://mikanani.me/                                                                              
Connecting to mikanani.me (mikanani.me)|199.96.62.21|:443...
话说这容器时间真的有问题吧？我这里系统时间是20点38分，，

**Comment by BiFangKNT** [comment]
> > > 
> > 
> > 
> > 第一条命令没有反应，第二条命令返回：
> > 
> > * Trying 174.37.243.85:443...
> > * Trying [2a03:2880:f10f:83:face:b00c:0:25de]:443...
> > * Immediate connect fail for 2a03:2880:f10f:83:face:b00c:0:25de: Address not available
> > 
> > 第三条命令也没啥反应，应该是连不上。
> > 可是此前我已经在docker部署了clash，用的是我平时在用的节点，在群晖控制面板里也指定了代理服务器，上套件商店啥的时候，在yacd前端里也能看到正常的有连接，流量有使用，bgmi怎么会连不上呢，，
> 
> 那你要排查你的容器环境了，我建议你先试试不要过这些代理之类的网络设置。（毕竟总好过现在哪儿都连不上了 但具体是你哪个环节造成的网络问题我就没法这样帮你排障了。

话说你那边可以裸连三个数据源吗？

**Comment by BiFangKNT** [comment]
> > > 
> > 
> > 
> > 第一条命令没有反应，第二条命令返回：
> > 
> > * Trying 174.37.243.85:443...
> > * Trying [2a03:2880:f10f:83:face:b00c:0:25de]:443...
> > * Immediate connect fail for 2a03:2880:f10f:83:face:b00c:0:25de: Address not available
> > 
> > 第三条命令也没啥反应，应该是连不上。
> > 可是此前我已经在docker部署了clash，用的是我平时在用的节点，在群晖控制面板里也指定了代理服务器，上套件商店啥的时候，在yacd前端里也能看到正常的有连接，流量有使用，bgmi怎么会连不上呢，，
> 
> 那你要排查你的容器环境了，我建议你先试试不要过这些代理之类的网络设置。（毕竟总好过现在哪儿都连不上了 但具体是你哪个环节造成的网络问题我就没法这样帮你排障了。

我测过我那边可以直连动漫花园，但是我把数据源切换到dhmy后cal，还是cal不动。于是我尝试使用：
curl -Lv https://share.dmhy.org
这个命令，结果立刻跳出了一堆结果，这个命令是有什么效果的？

**Comment by codysk** [comment]
容器里的时区不做设置的话是UTC时间，不影响的，在意的话就找找docker相关的教程挂载一下时区。
apk add 只是安装wget跟curl两个工具而已（我不记得原本有没有预装好了，跑一下总没错

访问不到数据源的话，在 bgmi 的[配置文件](https://github.com/BGmi/BGmi/tree/afed6e0cec56ca27ee43d0fb301a7fc38f835020#%E9%85%8D%E7%BD%AE-bgmi)里可以用以下配置用镜像站替换默认的萌番组跟动漫花园访问地址。
bangumi_moe_url = "https://bangumi.moe"
share_dmhy_url = "https://share.dmhy.org"

如果要用容器网络层面的代理方案，那你得自己调通网络先。

**Comment by codysk** [comment]
> > > > 
> > > 
> > > 
> > > 第一条命令没有反应，第二条命令返回：
> > > 
> > > * Trying 174.37.243.85:443...
> > > * Trying [2a03:2880:f10f:83:face:b00c:0:25de]:443...
> > > * Immediate connect fail for 2a03:2880:f10f:83:face:b00c:0:25de: Address not available
> > > 
> > > 第三条命令也没啥反应，应该是连不上。
> > > 可是此前我已经在docker部署了clash，用的是我平时在用的节点，在群晖控制面板里也指定了代理服务器，上套件商店啥的时候，在yacd前端里也能看到正常的有连接，流量有使用，bgmi怎么会连不上呢，，
> > 
> > 
> > 那你要排查你的容器环境了，我建议你先试试不要过这些代理之类的网络设置。（毕竟总好过现在哪儿都连不上了 但具体是你哪个环节造成的网络问题我就没法这样帮你排障了。
> 
> 我测过我那边可以直连动漫花园，但是我把数据源切换到dhmy后cal，还是cal不动。于是我尝试使用： curl -Lv https://share.dmhy.org 这个命令，结果立刻跳出了一堆结果，这个命令是有什么效果的？

只是个访问url的命令行工具而已。

**Comment by BiFangKNT** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 第一条命令没有反应，第二条命令返回：
> > > > 
> > > > * Trying 174.37.243.85:443...
> > > > * Trying [2a03:2880:f10f:83:face:b00c:0:25de]:443...
> > > > * Immediate connect fail for 2a03:2880:f10f:83:face:b00c:0:25de: Address not available
> > > > 
> > > > 第三条命令也没啥反应，应该是连不上。
> > > > 可是此前我已经在docker部署了clash，用的是我平时在用的节点，在群晖控制面板里也指定了代理服务器，上套件商店啥的时候，在yacd前端里也能看到正常的有连接，流量有使用，bgmi怎么会连不上呢，，
> > > 
> > > 
> > > 那你要排查你的容器环境了，我建议你先试试不要过这些代理之类的网络设置。（毕竟总好过现在哪儿都连不上了 但具体是你哪个环节造成的网络问题我就没法这样帮你排障了。
> > 
> > 
> > 我测过我那边可以直连动漫花园，但是我把数据源切换到dhmy后cal，还是cal不动。于是我尝试使用： curl -Lv https://share.dmhy.org 这个命令，结果立刻跳出了一堆结果，这个命令是有什么效果的？
> 
> 只是个访问url的命令行工具而已。

url可以访问，但却cal不动，这是怎么回事啊（笑哭）

**Comment by codysk** [comment]
返回了什么？

**Comment by BiFangKNT** [comment]
> 返回了什么？

返回了很长很长的一大串，估摸着有几十页，这是其中一页：
![image](https://user-images.githubusercontent.com/93891533/233786533-caaf4431-5b4c-40e0-b148-6a61319627b5.png)

**Comment by BiFangKNT** [comment]
> 返回了什么？

第三条命令我也试了，也是返回了像这样的一大串

**Comment by BiFangKNT** [comment]
> 返回了什么？

突然又可以cal出来了！谢谢大佬指点！
![image](https://user-images.githubusercontent.com/93891533/233787152-d777c4e9-7c79-451b-aa68-0bc8704cf181.png)

另外请教一下，可以添加数据源吗？我想用爱恋bt可以吗？

**Comment by codysk** [comment]
https://github.com/BGmi/BGmi/tree/afed6e0cec56ca27ee43d0fb301a7fc38f835020#bgmi-%E6%95%B0%E6%8D%AE%E6%BA%90
现在不支持，但可以按照这里的说明自己写写脚本提PR添加支持(

**Comment by BiFangKNT** [comment]
> https://github.com/BGmi/BGmi/tree/afed6e0cec56ca27ee43d0fb301a7fc38f835020#bgmi-%E6%95%B0%E6%8D%AE%E6%BA%90 现在不支持，但可以按照这里的说明自己写写脚本提PR添加支持(

但是大佬还有问题，你看我cal出来的列表，这很明显不是四月新番吧，好像混杂了很多季度的番剧，这要咋整啊？

**Comment by codysk** [comment]
https://share.dmhy.org/cms/page/name/programme.html
因为动漫花园的列表他确实就这样。。。

**Comment by BiFangKNT** [comment]
我去看了发现确实如此，这咋整啊（哭笑不得）

**Comment by BiFangKNT** [comment]
> https://share.dmhy.org/cms/page/name/programme.html 因为动漫花园的列表他确实就这样。。。

蜜柑计划有镜像站吗？

**Comment by codysk** [comment]
目前只有萌番组跟动漫花园支持配置镜像站，现在 mikan 也开始访问不了了吗？

**Comment by BiFangKNT** [comment]
> 目前只有萌番组跟动漫花园支持配置镜像站，现在 mikan 也开始访问不了了吗？

我去贴吧里看了，从4月20日开始就有人反应上不去了，我也是差不多那个时候发现fetch不到数据的

**Comment by codysk** [comment]
这样子，那建议先用着萌番组先，支持配置镜像站不难，只是不知道啥时候才有人将镜像站搭建起来有得用。

**Comment by BiFangKNT** [comment]
> 这样子，那建议先用着萌番组先，支持配置镜像站不难，只是不知道啥时候才有人将镜像站搭建起来有得用。

那萌番组有好用的镜像站吗？动漫花园好像并不好用

**Comment by codysk** [comment]
那得网上找找看咯，这项目只是做个工具，镜像站服务得别处翻翻~

**Comment by BiFangKNT** [comment]
> 那得网上找找看咯，这项目只是做个工具，镜像站服务得别处翻翻~

那大佬你是用哪个的，怎么用的啊

**Comment by BiFangKNT** [comment]
听吧友说好像三个站是同时炸的，可能是共用的某个的节点炸了？

**Comment by BiFangKNT** [comment]
蜜柑说被墙了

**Comment by codysk** [comment]
我部署的地方可以直连，所以我平时其实不用镜像(

**Comment by BiFangKNT** [comment]
> 我部署的地方可以直连，所以我平时其实不用镜像(

羡慕死了！

**Comment by BiFangKNT** [comment]
萌番组好像没有镜像站啊

**Comment by BiFangKNT** [comment]
> 容器里的时区不做设置的话是UTC时间，不影响的，在意的话就找找docker相关的教程挂载一下时区。 apk add 只是安装wget跟curl两个工具而已（我不记得原本有没有预装好了，跑一下总没错
> 
> 访问不到数据源的话，在 bgmi 的[配置文件](https://github.com/BGmi/BGmi/tree/afed6e0cec56ca27ee43d0fb301a7fc38f835020#%E9%85%8D%E7%BD%AE-bgmi)里可以用以下配置用镜像站替换默认的萌番组跟动漫花园访问地址。 bangumi_moe_url = "https://bangumi.moe" share_dmhy_url = "https://share.dmhy.org"
> 
> 如果要用容器网络层面的代理方案，那你得自己调通网络先。

话说这个“容器网络层面的代理方案”，具体要怎么搞啊，调通网络具体是指什么？

**Comment by BiFangKNT** [comment]
我如果做旁路由，在旁路由里做代理，可以让容器直接科学上网吗

**Comment by BiFangKNT** [comment]
萌番组的镜像站没找到，蜜柑的镜像站倒是找到了，有没有什么办法可以设置使用蜜柑的镜像站？

**Comment by codysk** [comment]
> > 容器里的时区不做设置的话是UTC时间，不影响的，在意的话就找找docker相关的教程挂载一下时区。 apk add 只是安装wget跟curl两个工具而已（我不记得原本有没有预装好了，跑一下总没错
> 
> > 
> 
> > 访问不到数据源的话，在 bgmi 的[配置文件](https://github.com/BGmi/BGmi/tree/afed6e0cec56ca27ee43d0fb301a7fc38f835020#%E9%85%8D%E7%BD%AE-bgmi)里可以用以下配置用镜像站替换默认的萌番组跟动漫花园访问地址。 bangumi_moe_url = "https://bangumi.moe" share_dmhy_url = "https://share.dmhy.org"
> 
> > 
> 
> > 如果要用容器网络层面的代理方案，那你得自己调通网络先。
> 
> 
> 
> 话说这个“容器网络层面的代理方案”，具体要怎么搞啊，调通网络具体是指什么？

就是别跟之前一样弄到容器内网都连不上

**Comment by codysk** [comment]
> 我如果做旁路由，在旁路由里做代理，可以让容器直接科学上网吗

这个要你自己找资料折腾了，我这没法提供这方面信息

**Comment by codysk** [comment]
> 萌番组的镜像站没找到，蜜柑的镜像站倒是找到了，有没有什么办法可以设置使用蜜柑的镜像站？

目前只有萌番组与dmhy支持镜像站配置，mikan的支持还得等等

**Comment by BiFangKNT** [comment]
得，现在连dhmy都上不了了，看个动画太难了（笑哭）

**Comment by BiFangKNT** [comment]
> > 萌番组的镜像站没找到，蜜柑的镜像站倒是找到了，有没有什么办法可以设置使用蜜柑的镜像站？
> 
> 目前只有萌番组与dmhy支持镜像站配置，mikan的支持还得等等

希望大佬把蜜柑的镜像站设置提上日程（笑哭）

**Comment by codysk** [comment]
有没有镜像站地址，我看下数据能不能解析

**Comment by BiFangKNT** [comment]
> 有没有镜像站地址，我看下数据能不能解析

https://mikanani.hacgn.fun

**Comment by codysk** [comment]
> > 有没有镜像站地址，我看下数据能不能解析
> 
> https://mikanani.hacgn.fun

尝试一下 1.3.7 版本的镜像，里边BGmi多一个 `mikan_url` 的配置项用来支持配置 mikan 的镜像站

**Comment by BiFangKNT** [comment]
> > > 有没有镜像站地址，我看下数据能不能解析
> > 
> > 
> > https://mikanani.hacgn.fun
> 
> 尝试一下 1.3.7 版本的镜像，里边BGmi多一个 `mikan_url` 的配置项用来支持配置 mikan 的镜像站

可以cal到列表了！！谢谢大佬！！！
