### ISSUE TITLE
没有更改transmission的任何设置，但却提示连接transmission超时

### ISSUE THREAD

**Issue by Mister-album** [codysk/bgmi-docker-all-in-one#14]
我是使用了http代理来访问蜜桔的，不知道是不是这个原因导致的？
![image](https://user-images.githubusercontent.com/51018113/234002509-62b005f5-c172-4365-ab7f-8cd2a667ded7.png)
![image](https://user-images.githubusercontent.com/51018113/234002610-3274e83d-e494-4afc-9e04-afc70d749ecf.png)

**Comment by album-GitHub** [comment]
测试了一下，用蜜柑的镜像站取消掉代理就没问题

**Comment by codysk** [comment]
如果是需要经过代理才能访问站点的话，要确保 http 代理也对 transmission-daemon 进程生效，否则添加下载任务的时候 transmission 会因为下载种子文件超时从而引发 rpc 超时。

- 可以尝试下创建容器的时候直接对容器配置 `http_proxy` 与 `https_proxy` 的环境变量而不是使用 bgmi 配置文件里的那个 proxy 配置
- 或者直接使用镜像站

**Comment by Mister-album** [comment]
> 如果是需要经过代理才能访问站点的话，要确保 http 代理也对 transmission-daemon 进程生效，否则添加下载任务的时候 transmission 会因为下载种子文件超时从而引发 rpc 超时。
> 
> * 可以尝试下创建容器的时候直接对容器配置 `http_proxy` 与 `https_proxy` 的环境变量而不是使用 bgmi 配置文件里的那个 proxy 配置
> * 或者直接使用镜像站

使用镜像站点后确实没有这个问题了，容器代理的话晚些测试一下
