### ISSUE TITLE
能fetch到数据，但部分番剧无法下载

### ISSUE THREAD

**Issue by BiFangKNT** [codysk/bgmi-docker-all-in-one#15]
事情要从我为了配置蜜柑镜像站，而把bgmi升级到最新版本开始说起
详情如下：
升级版本前，我已经将四月新番要追的都订阅了，并且基本都下载了一集以上。升级之后，我把配置文件添加镜像源，然后通过

`bgmi source mikan_project`

命令把数据源切换到蜜柑，然后通过web前端配合命令行将先前订阅过的番剧重新订阅了，并且通过fetch命令都确认了可以拉取到数据，而且我也确认过每个番剧的episode信息，确认是和我已经下载了的集数相对应。然后我通过

`bgmi update -d`

更新下载番剧。此时我以为bgmi如往常一样正常地把所有缺失的集数都下载了。

直到今天我进文件夹看才发现，其中一部番剧不仅没下载新的集数，连原先已经下载了的第一集都不见了。
于是我首先尝试先fetch一下，发现是能正常fetch到有三集的，但是当我输入下载命令后，却没有正常地下载：
![image](https://user-images.githubusercontent.com/93891533/234051871-db59acbe-4fd8-4465-8c8c-92eb649c5dd1.png)

并且我确认我番剧设置的已下载集数是1：
![image](https://user-images.githubusercontent.com/93891533/234052158-5bc7e5e6-5a44-4407-9115-85f011a3cd03.png)

于是我尝试先把文件夹整个删除，取消订阅，再重新订阅，并且设置episode为0：
```
bgmi delete "偶像大师 灰姑娘女孩 U149"
bgmi add "偶像大师 灰姑娘女孩 U149" --episode 0 --save-path './偶像大师 灰姑娘女孩 U149/'
```
但是仍然无效，而且并不会重新生成文件夹，请问这是怎么回事啊？

**Comment by BiFangKNT** [comment]
补图，上面的是list：
![image](https://user-images.githubusercontent.com/93891533/234055947-a15563fb-5f8b-4e17-9b5a-c3b1a4b70b45.png)

**Comment by codysk** [comment]
![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png)
我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了

**Comment by BiFangKNT** [comment]
> ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了

如果过滤掉了的话也fetch不出来啊，而且我也试过把过滤词删了，一样下不了了。

**Comment by BiFangKNT** [comment]
> ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了

![image](https://user-images.githubusercontent.com/93891533/234319806-f5629021-dbc0-462c-85ad-858fe2a32276.png)
等等，我把字幕组的过滤词删了就可以下了，这是怎么回事啊？貌似是名字前面是0的不能下，是1以上的可以下？这个数字是什么意思？为什么会这样？而且更新以前我记得很清楚lolihouse的这个资源是可以下的，现在不行了。

**Comment by codysk** [comment]
> > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> 
> ![image](https://user-images.githubusercontent.com/93891533/234319806-f5629021-dbc0-462c-85ad-858fe2a32276.png) 等等，我把字幕组的过滤词删了就可以下了，这是怎么回事啊？貌似是名字前面是0的不能下，是1以上的可以下？这个数字是什么意思？为什么会这样？而且更新以前我记得很清楚lolihouse的这个资源是可以下的，现在不行了。

那这个可能是影响到剧集集数的识别了，各家字幕组的标题啥风格都有，这个不太好办，只能先找些能正常识别的订阅了

**Comment by BiFangKNT** [comment]
> > > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/93891533/234319806-f5629021-dbc0-462c-85ad-858fe2a32276.png) 等等，我把字幕组的过滤词删了就可以下了，这是怎么回事啊？貌似是名字前面是0的不能下，是1以上的可以下？这个数字是什么意思？为什么会这样？而且更新以前我记得很清楚lolihouse的这个资源是可以下的，现在不行了。
> 
> 那这个可能是影响到剧集集数的识别了，各家字幕组的标题啥风格都有，这个不太好办，只能先找些能正常识别的订阅了

可是我记得Lolihouse这三个资源我之前是能正常下的啊，为啥现在下不了了（笑哭）

**Comment by BiFangKNT** [comment]
> > > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/93891533/234319806-f5629021-dbc0-462c-85ad-858fe2a32276.png) 等等，我把字幕组的过滤词删了就可以下了，这是怎么回事啊？貌似是名字前面是0的不能下，是1以上的可以下？这个数字是什么意思？为什么会这样？而且更新以前我记得很清楚lolihouse的这个资源是可以下的，现在不行了。
> 
> 那这个可能是影响到剧集集数的识别了，各家字幕组的标题啥风格都有，这个不太好办，只能先找些能正常识别的订阅了

有lolihouse的我都会下lolihouse的，所以我记得很清楚我之前下的就是lolihouse的

**Comment by BiFangKNT** [comment]
> > > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/93891533/234319806-f5629021-dbc0-462c-85ad-858fe2a32276.png) 等等，我把字幕组的过滤词删了就可以下了，这是怎么回事啊？貌似是名字前面是0的不能下，是1以上的可以下？这个数字是什么意思？为什么会这样？而且更新以前我记得很清楚lolihouse的这个资源是可以下的，现在不行了。
> 
> 那这个可能是影响到剧集集数的识别了，各家字幕组的标题啥风格都有，这个不太好办，只能先找些能正常识别的订阅了

而且还有一个问题没解决，就是我之前下好了的集数怎么突然间没了，导致我现在要从第一集开始下（笑哭）

**Comment by codysk** [comment]
> > > > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/93891533/234319806-f5629021-dbc0-462c-85ad-858fe2a32276.png) 等等，我把字幕组的过滤词删了就可以下了，这是怎么回事啊？貌似是名字前面是0的不能下，是1以上的可以下？这个数字是什么意思？为什么会这样？而且更新以前我记得很清楚lolihouse的这个资源是可以下的，现在不行了。
> > 
> > 
> > 那这个可能是影响到剧集集数的识别了，各家字幕组的标题啥风格都有，这个不太好办，只能先找些能正常识别的订阅了
> 
> 而且还有一个问题没解决，就是我之前下好了的集数怎么突然间没了，导致我现在要从第一集开始下（笑哭）

这个我这边没有复现出来，具体是怎么个流程操作流程弄出来的。

**Comment by BiFangKNT** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/93891533/234319806-f5629021-dbc0-462c-85ad-858fe2a32276.png) 等等，我把字幕组的过滤词删了就可以下了，这是怎么回事啊？貌似是名字前面是0的不能下，是1以上的可以下？这个数字是什么意思？为什么会这样？而且更新以前我记得很清楚lolihouse的这个资源是可以下的，现在不行了。
> > > 
> > > 
> > > 那这个可能是影响到剧集集数的识别了，各家字幕组的标题啥风格都有，这个不太好办，只能先找些能正常识别的订阅了
> > 
> > 
> > 而且还有一个问题没解决，就是我之前下好了的集数怎么突然间没了，导致我现在要从第一集开始下（笑哭）
> 
> 这个我这边没有复现出来，具体是怎么个流程操作流程弄出来的。

不清楚，更新之后偶尔发现的。首先是由于我在将所有订阅番剧一起update之后，第二天在jellyfin里发现u149这个番还是只有第一集（我之前下载的时候只更新了第一集），然后我就去命令行里单独对这个番update，发现仍然没有触发下载，再后来我逐一排查问题的时候，才发现文件夹里连第一集都不见了，单集的文件夹倒是还在，里面的season.nfo文件也在，但是视频和与视频名字一样的nfo文件都不见了（jellyfin里还能看到第一集大概是因为数据没刷新吧，应该是播放不了的，不过我没试验过就把文件夹删了）

**Comment by BiFangKNT** [comment]
> ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了

话说你尝试一下能不能下载lolihouse的这三个资源？

**Comment by codysk** [comment]
没法复现的话也就没法排查了吖，如果按理来说除非手动删除，像在下载器上选了删除种子以及文件之类的，BGmi本身是不会操作已下载的番剧文件的。先不管他继续观察下吧

**Comment by codysk** [comment]
> > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> 
> 话说你尝试一下能不能下载lolihouse的这三个资源？

不行，集数没识别出来，都当成第 0 话跳过了

**Comment by BiFangKNT** [comment]
> > > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> > 
> > 
> > 话说你尝试一下能不能下载lolihouse的这三个资源？
> 
> 不行，集数没识别出来，都当成第 0 话跳过了

难受了，再观察一下有没有别的问题吧，没有就凑合用了（笑哭）

**Comment by BiFangKNT** [comment]
> > > ![image](https://user-images.githubusercontent.com/5507434/234292115-9a40cb8c-1239-4462-8321-eb32cf2a7afa.png) 我用同样的番剧测试看起来能正常抓到剧集，有没有可能是你的过滤条件将剧集过滤没了
> > 
> > 
> > 话说你尝试一下能不能下载lolihouse的这三个资源？
> 
> 不行，集数没识别出来，都当成第 0 话跳过了

诶，我突然想，如果把已下载集数设置为-1，loli的资源是不是就能下了？

**Comment by codysk** [comment]
识别不到集数就没法自动一集一集自动抓，下载路径里的集数目录也没法组装

**Comment by BiFangKNT** [comment]
> 识别不到集数就没法自动一集一集自动抓，下载路径里的集数目录也没法组装

刚试过了，设置成-1确实能下载，只不过只能下载一集，我这里是下了loli的第三集。
还有这应该不是识别不到集数，而是不知道什么原因导致识别到的集数是第0集吧？（笑哭）

**Comment by codysk** [comment]
其实那些识别不到的都会当成 0

**Comment by codysk** [comment]
试下1.3.8版的镜像，这种格式能识别了

**Comment by BiFangKNT** [comment]
> 试下1.3.8版的镜像，这种格式能识别了

![image](https://user-images.githubusercontent.com/93891533/234478304-87f46f98-f9aa-4ffd-aebb-9875c3c471c5.png)
貌似ok了，谢谢大佬！
