### ISSUE TITLE
请问下载的番剧的文件夹里没有nfo文件，这是正常的吗？

### ISSUE THREAD

**Issue by BiFangKNT** [codysk/bgmi-docker-all-in-one#16]
如题，请问这是正常的吗？
我一直用jellyfin当媒体播放器，之前都用着好好的，但部分番剧最新的一话好几天了在jellyfin里都没被识别出来，我去检查文件夹发现，之前可以正常识别的剧集的文件夹里都有两个nfo文件，而未能识别的剧集的文件夹里却只有视频文件而没有nfo文件。

**Comment by codysk** [comment]
BGmi不会生成nfo文件，原来看到那些要么是字幕组种子带的，要么是jellyfin自己存的

**Comment by BiFangKNT** [comment]
> BGmi不会生成nfo文件，原来看到那些要么是字幕组种子带的，要么是jellyfin自己存的

那看来是jellyfin出问题了，一个星期了都没生成nfo文件
