### ISSUE TITLE
又出现不能识别的剧集格式了，希望跟进一下

### ISSUE THREAD

**Issue by BiFangKNT** [codysk/bgmi-docker-all-in-one#17]
最近不知道为什么在github这里上传不了图片，可以fetch一下偶像大师u149，lolihouse的第七集识别不了。

**Comment by BiFangKNT** [comment]
貌似v2版本的剧集都识别不了，之前的04v2也识别不到

**Comment by BiFangKNT** [comment]
话说最近docker不是被墙了吗，大佬有没有镜像站分享一下，我试过配置clash但是不知道为什么用不了，没有镜像的话我就更新不了bgmi了：（

**Comment by codysk** [comment]
可以将命令行以文本的形式贴上来

**Comment by BiFangKNT** [comment]
> 可以将命令行以文本的形式贴上来

其实就是之前出现过的部分剧集格式特殊，识别不到集数，显示成0了。命令行就是普通的fetch剧集的代码而已。

**Comment by BiFangKNT** [comment]
现在docker被墙的问题我已经搞定了，就等大佬出手了✪ ω ✪

**Comment by codysk** [comment]
需要提供具体的番剧名称。

**Comment by BiFangKNT** [comment]
> 需要提供具体的番剧名称。

上面说了鸭，《偶像大师 灰姑娘女孩 u149》

**Comment by BiFangKNT** [comment]
> 需要提供具体的番剧名称。

上面说了鸭，《偶像大师 灰姑娘女孩 u149》

**Comment by codysk** [comment]
日志里那个完整的title，带上第几集的那个

**Comment by BiFangKNT** [comment]
> 日志里那个完整的title，带上第几集的那个

额，日志是容器的日志吗

**Comment by codysk** [comment]
> > 日志里那个完整的title，带上第几集的那个
> 
> 
> 
> 额，日志是容器的日志吗

add / update 命令的日志

**Comment by BiFangKNT** [comment]
> > > 日志里那个完整的title，带上第几集的那个
> > 
> > 
> > 额，日志是容器的日志吗
> 
> add / update 命令的日志

这是fetch命令：
bgmi fetch "偶像大 灰姑娘女孩 U149"                                                                     
Followed subtitle group: LoliHouse                                                                                                   
Include keywords:                                                                                                                    
Exclude keywords:                                                                                                                    
Regular expression: (简|chs|CHS|gb|GB)                                                                                               
2023-06-03 05:21:17 INFO    | Fetch bangumi 偶像大师 灰姑娘女孩 U149 ...                                                             
8 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 08 [WebRip 1080p HEVC-10bit 
AAC][简繁日内封字幕]                                                                                                                 
0 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 07v2 [WebRip 1080p HEVC-10bi
t AAC][简繁日内封字幕]                                                                                                               
6 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 06 [WebRip 1080p HEVC-10bit 
AAC][简繁日内封字幕]                                                                                                                 
5 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 05 [WebRip 1080p HEVC-10bit 
AAC][简繁日内封字幕]                                                                                                                 
0 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 04v2 [WebRip 1080p HEVC-10bi
t AAC][简繁日内封字幕]                                                                                                               
4 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 04 [WebRip 1080p HEVC-10bit 
AAC][简繁日内封字幕]                                                                                                                 
3 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 03 [WebRip 1080p HEVC-10bit 
AAC][简繁日内封字幕]                                                                                                                 
2 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 02 [WebRip 1080p HEVC-10bit 
AAC][简繁日内封字幕]                                                                                                                 
1 | [喵萌Production&LoliHouse] 偶像大师 灰姑娘女孩 U149 / THE [email protected] CINDERELLA GIRLS U149 - 01 [WebRip 1080p HEVC-10bit 
AAC][简繁日内封字幕]

由于我第八集是能正常识别的，因此bgmi已经自动更新到第八集了，所以现在再用update命令是不会下载之前的剧集的，除非手动mark集数。不过没必要了吧，毕竟正是之前第七集识别不到，所以才没有下载的。我进文件夹里看也是有第八集的文件夹，没有第七集的。

**Comment by BiFangKNT** [comment]
最上面我的命令里虽然显示的是“偶像大 灰姑娘女孩 U149”，但实际上命令行里输入的是完整正确的标题的，只是我的浏览器插件导致网页的显示有点小问题，这个不影响的。

**Comment by codysk** [comment]
试试 1.3.11 的镜像，应该能行了~
