### ISSUE TITLE
又出现无法识别的剧集了，望更新

### ISSUE THREAD

**Issue by BiFangKNT** [codysk/bgmi-docker-all-in-one#18]
如题，本季新番：“LoveLive！虹咲学园学园偶像同好会 NEXT SKY”目前所有剧集都无法识别

**Comment by BiFangKNT** [comment]
另外，一直以来似乎都无法获取到蜜柑的剧场版分类的数据？是否有办法改进一下？

**Comment by BiFangKNT** [comment]
另外，虹团是ova分类的，应该也是这个原因才无法识别吧，不过不知道为什么在bgmi里被分类到星期天里了

**Comment by codysk** [comment]
应该是解析的时候将ova丢到礼拜天理了，bgmi本身主要还是解析礼拜一到礼拜天定期更新的番剧（包括日历的解析也是），所以这种OVA的话要下载的话还是用search命令直接查出来下吧。

**Comment by BiFangKNT** [comment]
> 应该是解析的时候将ova丢到礼拜天理了，bgmi本身主要还是解析礼拜一到礼拜天定期更新的番剧（包括日历的解析也是），所以这种OVA的话要下载的话还是用search命令直接查出来下吧。

害，只能这样了。

不过还有一个问题，就是web端经常出现一直转圈圈的情况，提示什么“获取日历失败，请检查网络”之类的，不管它放一会儿，过会儿再看又能正常载入进去了，这是怎么回事啊？这种情况出现得很频繁，现在是我一点订阅某个番剧，就会一直转圈圈，但是从命令行查看list的话，又能看到正常的订阅到这个番剧了，很明显不应该是普通的所谓的什么网络问题吧。

**Comment by BiFangKNT** [comment]
> 应该是解析的时候将ova丢到礼拜天理了，bgmi本身主要还是解析礼拜一到礼拜天定期更新的番剧（包括日历的解析也是），所以这种OVA的话要下载的话还是用search命令直接查出来下吧。

而我订阅成功某个番剧后，再点查看进行设置这个番剧的筛选设置的话，却又能正常显示保存成功，不会出现转圈圈的情况。

**Comment by BiFangKNT** [comment]
> 应该是解析的时候将ova丢到礼拜天理了，bgmi本身主要还是解析礼拜一到礼拜天定期更新的番剧（包括日历的解析也是），所以这种OVA的话要下载的话还是用search命令直接查出来下吧。

它这个订阅番剧转圈圈的情况，是整个web端都要转圈圈了，即使刷新网页，点击其他的选项，也都是转圈圈
