### ISSUE TITLE
为啥订阅了，update --download 下载器没反应？

### ISSUE THREAD

**Issue by RTGTX7** [codysk/bgmi-docker-all-in-one#19]
![屏幕截图 2023-08-08 042936](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/caa74e1d-4a1d-4b9c-9901-d1c601770e94)
为啥订阅了，update --download 下载器没反应？

以下是配置

data_source = "bangumi_moe"
download_delegate = "transmission-rpc"
tmp_path = "/bgmi/conf/bgmi/tmp"
proxy = ""
save_path = "/bgmi/bangumi"
front_static_path = "/bgmi/conf/bgmi/front_static"
db_path = "/bgmi/conf/bgmi/bangumi.db"
script_path = "/bgmi/conf/bgmi/scripts"
tools_path = "/bgmi/conf/bgmi/tools"
max_path = 3
bangumi_moe_url = "https://bangumi.moe" # Setting bangumi.moe url
share_dmhy_url = "https://share.dmhy.org" # Setting share.dmhy.org url
mikan_url = "https://mikanani.me" # Setting mikanani.me url
mikan_username = ""
mikan_password = ""
lang = "zh_cn"
enable_global_include_keywords = false
global_include_keywords = ["1080"]
enable_global_filters = true # enable global filter
global_filters = ["Leopard-Raws", "hevc", "x265", "c-a Raws", "U3-Web"] # Global exclude keywords
rpc_path = "/transmission/rpc"
rpc_host = "127.0.0.1"

[http]
admin_token = "admin"
danmaku_api_url = "" # danmaku api url, https://github.com/DIYgod/DPlayer#related-projects
serve_static_files = false

[aria2]
rpc_url = "http://127.0.0.1:6800/rpc"
rpc_token = "token:"

[transmission]
rpc_host = "127.0.0.1"
rpc_port = 9091
rpc_username = "your_username"
rpc_password = "your_password"
rpc_path = "/transmission/rpc"

[qbittorrent]
rpc_host = "127.0.0.1"
rpc_port = 8080
rpc_username = "admin"
rpc_password = "adminadmin"
category = ""

[deluge]
rpc_url = "http://127.0.0.1:8112/json"
rpc_password = "deluge"

[save_path_map] # per-bangumi save path

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/33e3da0a-2cf8-4d2a-a739-c615044e90bf)

**Comment by RTGTX7** [comment]
地址填的没错应该可以解析的呀

**Comment by RTGTX7** [comment]
还有我群辉也是也下载不出来， 个人问题？？？

**Comment by RTGTX7** [comment]
试了all-in-on 的下载器 和 群辉套件里的下载器都不行。我是这样配置的
[transmission]
rpc_host = "192.168.2.24"
rpc_port = 9091
rpc_username = "your_username"
rpc_password = "your_password"
rpc_path = "/transmission/rpc"

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/39a67ac6-879a-4b21-a802-075409db2bc9)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/a0d28a99-d0be-4f63-9580-f76a6a811375)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/d0e9f4db-5164-43e3-8e82-93610c3d202d)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/d2cea55b-e880-4955-a029-d01985434aea)

**Comment by RTGTX7** [comment]
页面有有网络配置，可以更新，也可以订阅，订阅了会在番剧栏里面，可是就是不下载。用了gbmi update --download 没用。感觉环境和配置都没啥问题也看网上其他人配置也就这样的说。就是不行。

我参考这些
https://post.smzdm.com/p/a0qm42ww/
https://syra-ti.icu/

**Comment by codysk** [comment]
> 
> 
> ![屏幕截图 2023-08-08 042936](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/caa74e1d-4a1d-4b9c-9901-d1c601770e94)
> 
> 为啥订阅了，update --download 下载器没反应？
> 
> 
> 
> 以下是配置
> 
> 
> 
> data_source = "bangumi_moe"
> 
> download_delegate = "transmission-rpc"
> 
> tmp_path = "/bgmi/conf/bgmi/tmp"
> 
> proxy = ""
> 
> save_path = "/bgmi/bangumi"
> 
> front_static_path = "/bgmi/conf/bgmi/front_static"
> 
> db_path = "/bgmi/conf/bgmi/bangumi.db"
> 
> script_path = "/bgmi/conf/bgmi/scripts"
> 
> tools_path = "/bgmi/conf/bgmi/tools"
> 
> max_path = 3
> 
> bangumi_moe_url = "https://bangumi.moe" # Setting bangumi.moe url
> 
> share_dmhy_url = "https://share.dmhy.org" # Setting share.dmhy.org url
> 
> mikan_url = "https://mikanani.me" # Setting mikanani.me url
> 
> mikan_username = ""
> 
> mikan_password = ""
> 
> lang = "zh_cn"
> 
> enable_global_include_keywords = false
> 
> global_include_keywords = ["1080"]
> 
> enable_global_filters = true # enable global filter
> 
> global_filters = ["Leopard-Raws", "hevc", "x265", "c-a Raws", "U3-Web"] # Global exclude keywords
> 
> rpc_path = "/transmission/rpc"
> 
> rpc_host = "127.0.0.1"
> 
> 
> 
> [http]
> 
> admin_token = "admin"
> 
> danmaku_api_url = "" # danmaku api url, https://github.com/DIYgod/DPlayer#related-projects
> 
> serve_static_files = false
> 
> 
> 
> [aria2]
> 
> rpc_url = "http://127.0.0.1:6800/rpc"
> 
> rpc_token = "token:"
> 
> 
> 
> [transmission]
> 
> rpc_host = "127.0.0.1"
> 
> rpc_port = 9091
> 
> rpc_username = "your_username"
> 
> rpc_password = "your_password"
> 
> rpc_path = "/transmission/rpc"
> 
> 
> 
> [qbittorrent]
> 
> rpc_host = "127.0.0.1"
> 
> rpc_port = 8080
> 
> rpc_username = "admin"
> 
> rpc_password = "adminadmin"
> 
> category = ""
> 
> 
> 
> [deluge]
> 
> rpc_url = "http://127.0.0.1:8112/json"
> 
> rpc_password = "deluge"
> 
> 
> 
> [save_path_map] # per-bangumi save path

你在第一次update的时候没带 --download 于是番剧索引更新到4了，然后你再运行 update --download 的时候实际上是在找4之后的集数

**Comment by codysk** [comment]
要重置当前集数可以用 bgmi mark 命令

**Comment by RTGTX7** [comment]
> 要重置当前集数可以用 bgmi mark 命令

不是重置问题吧，就是下载不了，我删了又重新配置，删了又重新配置。

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/9cf88440-e6f8-4bd1-b373-747385c89a8f)

**Comment by RTGTX7** [comment]
还是不行就是不下载

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/57fb898f-c3d5-4086-a590-19bb53bb027f)
啥问题？

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/54d499be-767e-4360-b84d-9f5a04186ea3)
试了一遍不行

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/88d7b5cf-4beb-42b4-bc53-a0c706ae5589)
大佬我懂了，谢谢~
