### ISSUE TITLE
视频解析失败

### ISSUE THREAD

**Issue by RTGTX7** [codysk/bgmi-docker-all-in-one#20]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/990577b7-72f0-47c3-892e-170c4b62c905)
这个视频解析失败是咋回事儿？

**Comment by RTGTX7** [comment]
我看了这个播放器是all in one里面自带有的，然后bgmi配置地址和下载器地址都指向同一个地方。

**Comment by RTGTX7** [comment]
这个是还要配置播放器地址？

**Comment by codysk** [comment]
你的transmission用的不是内置那个？

**Comment by codysk** [comment]
如果用外部的下载器的话，挂载目录时要确保容器内与下载器能用同样的路径访问到番剧存储目录。

**Comment by RTGTX7** [comment]
我现在用的内置。

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/a564f583-791d-440c-9b7c-7f338b01b672)

**Comment by codysk** [comment]
bangumi file 页面能看到番剧文件吗

**Comment by RTGTX7** [comment]
我发现谷歌浏览器有内置一个视频播放器的，以后可以添加吗？因为这个视频播放器有Chromecast，感觉投屏很好用。

**Comment by RTGTX7** [comment]
> bangumi file 页面能看到番剧文件吗

> 可以看见文件

**Comment by codysk** [comment]
> > bangumi file 页面能看到番剧文件吗
> 
> > 可以看见文件

那用F12在解析失败那个页面看看是哪个请求出问题了...

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/2142ed0e-cbc4-4d55-90a7-127aeb0b4fb9)

**Comment by RTGTX7** [comment]
还有个问题这个ui界面点击订阅多久自动更新下载任务？

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/ef78c6fb-8a83-4963-9e9d-f453ae8e6b10)

**Comment by RTGTX7** [comment]
Header 的问题？

**Comment by codysk** [comment]
404了，看起来确实找不到视频文件，是只有这一集不行还是所有文件都播不了？

自动更新会在每小时的0分和30分进行

**Comment by RTGTX7** [comment]
> 404了，看起来确实找不到视频文件，是只有这一集不行还是所有文件都播不了？
> 
> 自动更新会在每小时的0分和30分进行

所有的

**Comment by codysk** [comment]
> > 404了，看起来确实找不到视频文件，是只有这一集不行还是所有文件都播不了？
> > 
> > 自动更新会在每小时的0分和30分进行
> 
> 所有的

动过save path的设置么

**Comment by RTGTX7** [comment]
没有

**Comment by RTGTX7** [comment]
一直都是 /gbmi/bangumi/other

**Comment by RTGTX7** [comment]
data_source = "bangumi_moe"
download_delegate = "transmission-rpc"
tmp_path = "/bgmi/conf/bgmi/tmp"
proxy = ""
save_path = "/bgmi/bangumi/other"
front_static_path = "/bgmi/conf/bgmi/front_static"
db_path = "/bgmi/conf/bgmi/bangumi.db"
script_path = "/bgmi/conf/bgmi/scripts"
tools_path = "/bgmi/conf/bgmi/tools"
max_path = 3
bangumi_moe_url = "https://bangumi.moe" # Setting bangumi.moe url
share_dmhy_url = "https://share.dmhy.org" # Setting share.dmhy.org url
mikan_url = "https://mikanani.me" # Setting mikanani.me url
mikan_username = ""
mikan_password = ""
lang = "zh_cn"
enable_global_include_keywords = false
global_include_keywords = ["1080"]
enable_global_filters = false # enable global filter
global_filters = ["Leopard-Raws", "hevc", "x265", "c-a Raws", "U3-Web"] # Global exclude keywords

[http]
admin_token = "panda"
danmaku_api_url = "" # danmaku api url, https://github.com/DIYgod/DPlayer#related-projects
serve_static_files = false

[aria2]
rpc_url = "http://192.168.2.24:6800/rpc"
rpc_token = "token:"

[transmission]
rpc_host = "192.168.2.24"
rpc_port = 9090
rpc_username = "your_username"
rpc_password = "your_password"
rpc_path = "/transmission/rpc"

[qbittorrent]
rpc_host = "127.0.0.1"
rpc_port = 8080
rpc_username = "admin"
rpc_password = "adminadmin"
category = ""

[deluge]
rpc_url = "http://127.0.0.1:8112/json"
rpc_password = "deluge"

[save_path_map] # per-bangumi save path

**Comment by RTGTX7** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/59045163/1a7e5aa3-c0d7-4ce6-9e32-60a16e0079dc)

**Comment by codysk** [comment]
默认配置应该是不带other的，改回去然后手动移动一下番剧文件吧，或者考虑下清理干净用默认配置重新跑个容器以避免遇到更多的配置问题？

**Comment by RTGTX7** [comment]
> 默认配置应该是不带other的，改回去然后手动移动一下番剧文件吧，或者考虑下清理干净用默认配置重新跑个容器以避免遇到更多的配置问题？

好的

**Comment by RTGTX7** [comment]
> 默认配置应该是不带other的，改回去然后手动移动一下番剧文件吧，或者考虑下清理干净用默认配置重新跑个容器以避免遇到更多的配置问题？

改回默认路径就可以了，谢谢！

**Comment by RTGTX7** [comment]
但是！

**Comment by RTGTX7** [comment]
新问题来了，这个播放器好像不支持mkv封装的字幕唉

**Comment by codysk** [comment]
> 新问题来了，这个播放器好像不支持mkv封装的字幕唉

这事...浏览器上的播放器都不好解决，咱一般就过滤出提供mp4的字幕组来下了

**Comment by RTGTX7** [comment]
有啥调用本地播放器的方法？

**Comment by codysk** [comment]
> 有啥调用本地播放器的方法？

自己进目录点开文件播？

**Comment by RTGTX7** [comment]
打开文件夹，打开视频？然后选择本地播放器？白费了这么好的ui.

**Comment by RTGTX7** [comment]
点开文件夹播放，你这个项目就没啥灵魂了，这和rss订阅有啥区别？就差那么一点点了，大佬

**Comment by RTGTX7** [comment]
说实话市面上都没啥好的，番剧库存软件，plex什么的不适合vcb这种文件夹格式。非要第几季第几集，番剧还有ova，剧场版，特典，印刷，音乐cd。这些放一个文件夹下plex什么的就乱搞。

**Comment by RTGTX7** [comment]
大佬，这个可以解决追新番，即使挂在Window上让它每天自启都很强，尤其是b站删减很多内容什么的。
