### ISSUE TITLE
wget命令无法访问镜像站

### ISSUE THREAD

**Issue by BiFangKNT** [codysk/bgmi-docker-all-in-one#21]
> 无意中发现的，原因是今天进bgmi web的时候突然发现之前存在的番剧封面全都白了
> 到终端里用wget命令访问网址却失败了，抓头发了好一会儿
> 不过后来发现用curl访问的话却有结果
> 于是我用更新封面命令`bgmi cal --download-cover`重新下载了封面，正常下载好了：
> 
> ![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/cd7d9723-02ba-4ae0-b632-a1aeeaff65a7)
> 

再刷新web就能看到封面了。于是本来想提bug的，现在就换作提问吧：

1. 为什么封面会突然消失？
2. 为什么wget命令无法访问，curl命令却可以？

以下是我具体的排查过程：
用浏览器可以直连镜像站，没有挂梯的，但在bgmi终端里却无法访问，显示：`wget: can't connect to remote host (172.67.209.126): Host is unreachable`

> 镜像站地址：
> https://mikanime.tv/
> https://mikanani.hacgn.fun/

百度是可以的：
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/91c80675-d7d5-4a95-8c85-9031407491d7)

用wget命令访问不了，但用curl -Lv 命令却有结果：
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/910b09b1-3404-43c8-98bd-d4c46cb110e5)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/d68c509f-c8d8-4c3f-abad-eae24e409f2a)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/8752f6e4-081e-4b55-bea6-a618f865781c)

**Comment by codysk** [comment]
> 为什么封面会突然消失？

这得有得复现我才有办法查。。。

> 为什么wget命令无法访问，curl命令却可以？

wget 只会尝试连接解析出来的几个 ip 中的其中一个，正好那个你连不上，wget 就炸了，而 curl 在连接失败的时候会自动尝试下一个 ip ，于是乎他会试到连上或者将所有 ip 都试一次。

**Comment by BiFangKNT** [comment]
> wget 只会尝试连接解析出来的几个 ip 中的其中一个，正好那个你连不上，wget 就炸了，而 curl 在连接失败的时候会自动尝
试下一个 ip ，于是乎他会试到连上或者将所有 ip 都试一次。

哦，原来是这样，明白了

> 这得有得复现我才有办法查。。。

哈哈我也觉得很难排查，要不你留意一下？我记得虽然很偶然，但我不止一次遇到这种情况了。你没有遇到过吗？

**Comment by codysk** [comment]
确实没遇见过
