### ISSUE TITLE
无法更新番剧列表

### ISSUE THREAD

**Issue by BiFangKNT** [codysk/bgmi-docker-all-in-one#22]
不知道是不是bug，cal命令好像获取不到新番列表？显示的番剧依旧是旧的，而蜜柑官网列表已经更新了
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/6eb19dad-3795-4b20-80a9-3b4ee950fb5f)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/70968d92-8bf4-4610-bf7a-48ede7a9dd04)

**Comment by BiFangKNT** [comment]
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/71ad6eb8-d0c0-4585-a401-f7725bb70e58)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/93891533/a820449e-7e7d-466d-8c5e-cc338ed36327)
不知道图片能不能看到

**Comment by BiFangKNT** [comment]
发现了个更新列表的命令：`bgmi cal -f`，现在问题已经解决了
不过现在我有了一个新的疑问：难道列表更新不是自动的，而是需要手动更新的吗？

**Comment by codysk** [comment]
日历自动更新的频率是比抓番剧低不少的，可能正好在gap里边看到了。
