### ISSUE TITLE
fetch不到某些字幕组

### ISSUE THREAD

**Issue by huaji01** [codysk/bgmi-docker-all-in-one#23]
拿[葬送的芙莉莲]来举例，LoliHouse这个字幕组在蜜柑和bgmi web端都有显示
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/95219006/7f5d70b7-f718-4df3-bb61-1e825000e10c)

在控制台输入bgmi filter "葬送的芙莉莲"也有

![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/95219006/c2ab6230-91f2-4d17-a4d7-7881238089f6)
但是订阅了不下载，输入bgmi fetch ”葬送的芙莉莲“显示的数据里没有这个汉化组

订阅了这个汉化组后再fetch就会报错

![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/95219006/08c35182-e778-4a08-b5a5-24f3e4cf8c26)

这是什么问题

**Comment by codysk** [comment]
是不是这个字幕组的资源让 [global filter](https://github.com/BGmi/BGmi#%E6%8E%92%E9%99%A4) 给全部过滤掉了

**Comment by huaji01** [comment]
> 是不是这个字幕组的资源让 [global filter](https://github.com/BGmi/BGmi#%E6%8E%92%E9%99%A4) 给全部过滤掉了

感谢大佬回复，我试了下，确实是[global filter](https://github.com/BGmi/BGmi#%E6%8E%92%E9%99%A4)吧hevc给默认过滤掉了，现在已经解决了。不过我想多问一下为什么会默认过滤hevc，x265这些格式，是因为兼容性的原因吗。

**Comment by codysk** [comment]
> > 是不是这个字幕组的资源让 [global filter](https://github.com/BGmi/BGmi#%E6%8E%92%E9%99%A4) 给全部过滤掉了
> 
> 
> 
> 感谢大佬回复，我试了下，确实是[global filter](https://github.com/BGmi/BGmi#%E6%8E%92%E9%99%A4)吧hevc给默认过滤掉了，现在已经解决了。不过我想多问一下为什么会默认过滤hevc，x265这些格式，是因为兼容性的原因吗。

对的，主要就是在浏览器上的播放时的兼容性问题。 以前 hevc 在浏览器上基本就是都不能播，现在兼容情况好了不少，如果字幕组的封装方式你的浏览器能支持，或者主要不用浏览器来看，将 global filters 改掉就好。

**Comment by huaji01** [comment]
> > > 是不是这个字幕组的资源让 [global filter](https://github.com/BGmi/BGmi#%E6%8E%92%E9%99%A4) 给全部过滤掉了
> > 
> > 
> > 感谢大佬回复，我试了下，确实是[global filter](https://github.com/BGmi/BGmi#%E6%8E%92%E9%99%A4)吧hevc给默认过滤掉了，现在已经解决了。不过我想多问一下为什么会默认过滤hevc，x265这些格式，是因为兼容性的原因吗。
> 
> 对的，主要就是在浏览器上的播放时的兼容性问题。 以前 hevc 在浏览器上基本就是都不能播，现在兼容情况好了不少，如果字幕组的封装方式你的浏览器能支持，或者主要不用浏览器来看，将 global filters 改掉就好。

好的大佬我明白了，再次感谢您抽时间回复我。
