### ISSUE TITLE
docker版本，打开“calendar”、“subscribe”报错

### ISSUE THREAD

**Issue by 457992195** [codysk/bgmi-docker-all-in-one#24]
使用docker版本的bgmi，mikan作为数据源。
2024.1.1,上午正常使用，期间没有对bgmi做操作。到了下午，无法打开“calendar”、“subscribe”栏目（推测，之前老番都放完了，拉取最新24年1月份番剧的时候出问题了）。

![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/22525148/a39eeacd-8ca1-4fa7-8f48-c17c71b38ce1)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/22525148/6cdd571f-c1c6-440d-88d0-050e80455a68)
![image](https://github.com/codysk/bgmi-docker-all-in-one/assets/22525148/5cbc7dfa-95df-490a-9cfc-5e2e5ff39164)

bgmi version: 4.4.7
python version: 3.10.11 (main, Apr  6 2023, 01:16:54) [GCC 12.2.1 20220924]
os: Linux-5.19.17-Unraid-x86_64-with
arch: ('64bit', '')

**Comment by 457992195** [comment]
发现吧所有文件删除，重新装好了。
@codysk 还想问下，在新老番剧交替的时候，怎么强制刷新番剧列表，应为想手动更新下最新的番剧数据，使用“bgmi source mikan_project”命令的话，之前的集数九没了。

**Comment by 457992195** [comment]
找到了，使用“bgmi cal -f”可以强制更新获取最新bangumi日历

**Comment by codysk** [comment]
`bgmi cal --force-update --download-cover` 这样会连数据带封面图片重新拉一次

**Comment by 457992195** [comment]
> `bgmi cal --force-update --download-cover` 这样会连数据带封面图片重新拉一次

好的，谢谢
