### ISSUE TITLE
base image 中依赖的 cargo 导致 image 体积巨大

### ISSUE THREAD

**Issue by livelazily** [codysk/bgmi-docker-all-in-one#26]
cargo 安装时会依赖 rust, 装完后体积巨大.
<img width="637" alt="image" src="https://github.com/codysk/bgmi-docker-all-in-one/assets/449935/c4484728-bff4-4295-983b-bf00ee9ffb52">

搜了一圈代码, 好像没地方使用到 cargo; bgmi 的安装好像也没用到 cargo.
请问具体哪里使用了 cargo, 如果没有用到的话能否去掉这个依赖

**Comment by codysk** [comment]
这个其实是用 gh action 免费版构建的一个妥协，在每个版本构建的时候会用当前的版本对基础环境镜像做测试，这里的一些包在arm没有预编译版本，安装时就会依赖到cargo，而如果不在构建镜像的时候就将他装好而是在测试时整体临时安装测试的话构建就会超时，所以他就被塞到基础镜像里带去所有发布镜像去了。

**Comment by codysk** [comment]
[1.4](https://github.com/codysk/bgmi-docker-all-in-one/releases/tag/1.4) 版本镜像已经处理掉 cargo 了
