### ISSUE TITLE
能否把bgmi和transmission拆开，用docker-compose组合这两个容器？

### ISSUE THREAD

**Issue by Aquaakuma** [codysk/bgmi-docker-all-in-one#4]
能否把bgmi和transmission拆开，用docker-compose组合这两个容器？这样扩展性更强，可以自己更换喜欢的下载器，配置也是分开的，方便管理。

**Comment by codysk** [comment]
emmm 这个 all in one 的镜像目的就是起一个镜像就能开始用起来基础的功能，
如果要用它来搭配其他下载器的话 可以用 bgmi 的 config 命令自己配置想要用的下载器，
里边自带那个 transmission 也可以用 supervisor 来关掉。

回头我看看让他能从 env 注入下载器配置这样也许就更容易用 docker-composer 之类的编排工具来组合了。

**Comment by poseidon2750** [comment]
想请教如何用 supervisor关掉自带transmission？
或者在docker创建的时候可否提供选项：不启用内置的transmission

**Comment by codysk** [comment]
要关闭的话可以在容器中执行
`supervisorctl stop bgmi:transmission`
回头我再看下提供个选项去在容器初始化时不启动transmission，原来之所以没这么做是因为 bgmi 会将自己的 bangumi 目录提交到下载器作为下载目录，这意味着下载器必须能与bgmi用同一个路径访问到存储目录。感觉应该没多少人愿意折腾，所以没这么做hhh

**Comment by sbbbsbbb** [comment]
看来和我遇到同样的问题,我也在找关闭transmission的方法,主要是transmission如果直接重启进程,修改配置文件是无法生效的

**Comment by codysk** [comment]
在 [1.2.6](https://github.com/codysk/bgmi-docker-all-in-one/releases/tag/1.2.6) 版本开始，创建容器时可以用环境变量配置来禁用内置 transmission
