### ISSUE TITLE
在docker上部署后打开webui只有一个Index of的空白页面是怎么回事

### ISSUE THREAD

**Issue by giligili6661** [codysk/bgmi-docker-all-in-one#7]
在docker上有正常运行

**Comment by codysk** [comment]
具体访问的是哪个 url，以及 docker 容器的日志贴一下。
浏览器截图也贴一下看看。

**Comment by 1164278621** [comment]
同 我在群晖NAS中发现了这个问题
系统DSM：7.0.1-42218
![屏幕截图 2022-02-22 220222](https://user-images.githubusercontent.com/53553296/155148560-15e4b361-ede9-4803-af2c-0b5c75f7eab1.jpg)
![屏幕截图 2022-02-22 221044](https://user-images.githubusercontent.com/53553296/155149224-e5a86004-14be-4ac5-a1f3-aeb23741c0f0.jpg)
![屏幕截图 2022-02-22 221118](https://user-images.githubusercontent.com/53553296/155149341-b3423464-db06-45fb-b0b4-c2df7fccfa5f.jpg)

**Comment by codysk** [comment]
启动的时候，会从 `https://registry.cnpmjs.org` 下载前端资源，看 log 提示前端资源下载失败了
确认一下容器的网络连接然后再试几次 bgmi install 看看？

**Comment by codysk** [comment]
最新版将前端资源的下载点换成了 npmjs 官方源,可以使用最新版前端测试下

**Comment by codysk** [comment]
No further reply.
