### ISSUE TITLE
在docker里创建的文件夹是root 755，aria2无权限访问

### ISSUE THREAD

**Issue by Whuihuan** [codysk/bgmi-docker-all-in-one#8]
我用的是aria2-pro这个docker管理aria2，他默认是以nobody权限读取，但是bgmi-AIO的docker创建的文件夹都是root权限，导致aria2创建文件失败，有没有办法指定UID和GID创建文件？

**Comment by codysk** [comment]
试下将 bgmi 创建出来的存储 bangumi 文件夹直接 chown 给 aira2 用？

**Comment by Whuihuan** [comment]
> 试下将 bgmi 创建出来的存储 bangumi 文件夹直接 chown 给 aira2 用？

问题是出在bgmi在bangumi下面创建的番剧文件夹是这么个权限，导致aria2因为使用nobody权限无法读取，所以只能让bgmi创建777的文件夹或者让aria2以root权限运行解决。目前我只能让aria2以root权限运行了

**Comment by codysk** [comment]
问题应该不大，这段时间我看看

**Comment by codysk** [comment]
[1.2.7](https://github.com/codysk/bgmi-docker-all-in-one/releases/tag/1.2.7) 版本之后可以通过设置 
`OVERRIDE_USER=1000:1000` 
来定时维护bangumi目录的所有者，目前只是用定时任务维护的方式进行，创建时支持可能得从上游项目去做了

**Comment by codysk** [comment]
[1.2.8](https://github.com/codysk/bgmi-docker-all-in-one/releases/tag/1.2.8) 版本之后设置 `OVERRIDE_USER=1000:1000` 将以指定用户运行 bgmi
要用 nobody 的话可以 `OVERRIDE_USER=65534:65534`
